### ISSUE TITLE
deno2nix not working with newer nixpkgs

### ISSUE THREAD

**Issue by MordragT** [SnO2WMaN/deno2nix#3]
Hello,
first of all thank you for creating this flake.
I bumped into an error saying 
```
error: getting status of '/nix/store/345q8dyv6mx38bkj25rmykzq34p3x426-source/nix': No such file or directory
```
with newer versions of nixpkgs.
It seems like the `src` variable is somehow concatenated twice.

**Comment by SnO2WMaN** [comment]
Is there a repository that can reproduce this? On a different note, I am currently having a different issue (similar to https://github.com/denoland/deno/issues/14440) with this flake not working.

**Comment by MordragT** [comment]
Yes this https://github.com/MordragT/nix-template-deno simple template i created does not work currently.

**Comment by SnO2WMaN** [comment]
Thanks I will manage to do this problem

**Comment by SnO2WMaN** [comment]
@MordragT 

Two months ago my code for mkExecutable was catastrophically bad for no reason, but I fixed it. I also submitted a pull request at the same time ( https://github.com/MordragT/nix-template-deno/pull/1 ). Sorry for the long delay.

**Comment by MordragT** [comment]
Thank you for fixing it I just merged your PR.
